Add second dropdown
llwch/javascript.itechart pull request #10
Opened 2018-05-15 20:58 UTC by llwch

2) дроп-даун Model, содержащий hard-coded списки моделей для каждого производителя (список моделей хранится в массиве на клиенте и подтягивается сразу после выбора значения или его изменения в дроп-дауне Manufacturer)

2018-05-18 21:34 UTC, SergeBondar requested changes

2018-05-18 21:34 UTC, SergeBondar commented on website/js/main.js
> +function showManu(manufacturer) {
ты тут модели вроде показываешь
нужно другое название функции

2018-05-18 21:34 UTC, SergeBondar commented on website/js/main.js
> +            modelArray = mercedesModels
; всегда в конце выражения

2018-05-18 21:34 UTC, SergeBondar commented on website/js/main.js
> +        selectManufacturer.add(option);
а куда ты их добавляешь?

2018-05-22 08:43 UTC, llwch commented
All fixes are in: https://github.com/llwch/javascript.itechart/pull/11

2018-05-22 08:43 UTC, closed without merging