Website task 4 Add button and table with manufacturer and model
llwch/javascript.itechart pull request #11
Opened 2018-05-17 21:40 UTC by llwch

- without status and validation

2018-05-18 21:48 UTC, SergeBondar requested changes

2018-05-18 21:48 UTC, SergeBondar commented on website/js/main.js
> +    createTable(manuValue,modelValue,'Whut?');
пробелы

2018-05-18 21:48 UTC, SergeBondar commented on website/js/main.js
> +    tableLoc.appendChild(table);
вот это лучше сделать в последнюю очередь

2018-05-21 14:02 UTC, SergeBondar commented on website/index.html
> +        <option value=""selected>Select manufacturer</option>
пробелы между атрибутами

2018-05-21 14:02 UTC, SergeBondar commented on website/js/main.js
> +    document.getElementById('tableLocation').innerHTML='';
а в чем отличие от 41 строки? там правильней, кстати

2018-05-21 14:02 UTC, SergeBondar commented on website/js/main.js
> +    }else{
надо больше пробелов везде

2018-05-21 14:02 UTC, SergeBondar commented on website/js/main.js
> +    return modelStatus;
отступ?

2018-05-22 07:28 UTC, SergeBondar reviewed
и там пару отступов/пробелов

2018-05-22 07:28 UTC, SergeBondar commented on website/js/main.js
> +    var th = document.createElement('th');
тебе точно нужны эти tr/th?

2018-05-22 11:48 UTC, SergeBondar commented on website/js/main.js
> +    tr = document.createElement('tr');
объявление переменных?

2018-05-22 13:56 UTC, SergeBondar approved these changes

2018-05-24 14:53 UTC, MaxMarasanov approved these changes

2018-05-24 14:57 UTC, merged