Website task 4 (base site)
llwch/javascript.itechart pull request #9
Opened 2018-05-15 20:44 UTC by llwch

2018-05-16 09:07 UTC, SergeBondar requested changes

2018-05-16 09:07 UTC, SergeBondar commented on website/css/style.css
> +body{
пробел после селектора

2018-05-16 09:07 UTC, SergeBondar commented on website/css/style.css
> +    background-color:seashell;
пробел после :

2018-05-16 09:07 UTC, SergeBondar commented on website/index.html
> +    <p>Select manufacturer and Model below:</p>
давай сделаем это через <label "for=">

2018-05-16 09:07 UTC, SergeBondar commented on website/index.html
> +        <option value = "" selected>Select manufacturer</option>
а вот в атрибутах пробелы не ставим между =

2018-05-18 21:31 UTC, SergeBondar approved these changes

2018-05-22 08:42 UTC, closed without merging

2018-05-22 08:42 UTC, llwch commented
All fixes are in: https://github.com/llwch/javascript.itechart/pull/11